### ISSUE TITLE
DOCS: Update tutorial docs to explain the current version of vscode extension

### ISSUE THREAD

**Issue by joshuahannan** [onflow/vscode-flow#2]
### Issue To Be Solved

Revisit the tutorial docs in:
https://docs.onflow.org/docs/visual-studio-code-extension
and make sure that they still apply to the latest version of the extension, especially regarding the service account

**Comment by joshuahannan** [comment]
I'd like to assign this to myself, but don't have the ability. @turbolent @10thfloor can you help out?

**Comment by turbolent** [comment]
I don't have permissions either. @10thfloor an you please set permissions like in all other repositories:

- onflow/flow-admin ⇒ Admin access
- onflow/flow ⇒ Write access

**Comment by 10thfloor** [comment]
@joshuahannan Updated permissions per @turbolent

**Comment by psiemens** [comment]
Stale, closing
