### ISSUE TITLE
VS Code syntax highlighting is disabled after event declaration

### ISSUE THREAD

**Issue by joshuahannan** [onflow/vscode-flow#24]
### Problem

When declaring events, the next few lines after the event declaration do not get highlighted correctly.

### Steps to Reproduce

1. Copy this contract:
```
pub contract Test {

    pub event Event()

    pub event Second()

    pub var field: Int

    pub fun changeVar() {
        self.field = 1
    }
}
```
2. See that the fields after `Event` are not highlighted properly.

**Comment by turbolent** [comment]
@joshuahannan transferred this issue to the VS Code extension repo.

**Comment by psiemens** [comment]
Example of the bug:

![Screen Shot 2020-08-14 at 2 30 16 PM](https://user-images.githubusercontent.com/2547035/90294186-b129d680-de3a-11ea-9d00-0ae036755393.png)

**Comment by psiemens** [comment]
@turbolent @joshuahannan is this bug still present?

**Comment by c0wfunk** [comment]
Here's another example
![Screen Shot 2021-04-03 at 7 37 16 AM](https://user-images.githubusercontent.com/1836516/113477404-7e773180-944f-11eb-9d4b-7dc97598a9ff.png)
