### ISSUE TITLE
Move Flow client commands from language server to CLI

### ISSUE THREAD

**Issue by psiemens** [onflow/vscode-flow#35]
### Issue To Be Solved

Currently the VS Code extension creates accounts, deploys contracts, submits transactions and executes scripts by calling a _server-side_ command on the Cadence language server, and the language server then makes calls to the Flow Emulator (which it assumes is already running).

In my opinion, the language server shouldn't need to maintain a connection with the emulator, and ideally shouldn't need to sign transactions or manage accounts. As we move towards a more sophisticated local development environment, it will get harder to make sure the VS Code extension, language server and CLI work together and integrate properly.

### Suggest A Solution

I'd like to suggest that we phase out the Flow client commands in the language server. Instead, the code lens commands that show up (e.g. "submit transaction") can map to local Flow CLI calls. 

The benefit of this approach is threefold:
- The Cadence language server can be simplified to primarily focus on Cadence itself, rather than the more complicated Flow functionality
- New features can be introduced to the CLI in one place and then exposed to the VS Code extension. This means we won't have to reimplement logic in the language server that is already in the CLI
- Updates are coming to the CLI that allow local contract files to be automatically mapped to accounts on chain (i.e. emulator or testnet). By connecting to the CLI, the VS Code extension will be able to use these mappings to create a more seamless local development experience

Drawbacks
- This removes features from the language server, which may make it more difficult for other code editors to integrate with Flow.

**Comment by psiemens** [comment]
@turbolent I'd love to get your initial thoughts on this. 

@MaxStalker and I experimented this morning by updating the "submit transaction" code lens command to call this directly from the extension:

```
flow transactions send --code "path-to-cadence-file-from-code-lens"
```

It worked quite well!

**Comment by turbolent** [comment]
💯 This would be really great! This would make the language server much simpler and remove the dependency on the SDK. 

The only "problem" I can see is import resolution (e.g. resolving an import of an address, so it can be included when checking local file). But even if we plan to keep this feature, this could be done using the CLI.

**Comment by psiemens** [comment]
> The only "problem" I can see is import resolution (e.g. resolving an import of an address, so it can be included when checking local file). But even if we plan to keep this feature, this could be done using the CLI.

Good point. I'll think more about this!

**Comment by psiemens** [comment]
@MaxStalker As discussed this morning, it'd be great to start by updating the "submit transaction" code lens command to call the CLI rather than the language server. We won't be able to support arguments yet, but that's OK for now. 

Can you update this issue with your results? We can move onto other commands after we get that one working.

**Comment by psiemens** [comment]
Closing this in favour of https://github.com/onflow/flow-cli/issues/80
