### ISSUE TITLE
Update Syntax Highlighting

### ISSUE THREAD

**Issue by turbolent** [onflow/vscode-flow#6]
## Context

Since the release of the extension Cadence has gained some more features.
Make sure the grammar is up-to-date.

## Definition of Done

- [ ] Improve the syntax highlighting for Cadence by updating the grammar
  - [ ] Pragmas

**Comment by turbolent** [comment]
Why did this get closed?

**Comment by sideninja** [comment]
@DylanTinianov This would be a relevant improvement for current ongoing work. I would say adding pragma syntax highlighting as well as documentation around pragma would be nice.
